import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  header: {
    width: '100%',
    height: 50,
    backgroundColor: '#c4ffc4',
    flexDirection: 'row',
    alignItems: 'center',
    elevation: 10,
  },
  touchback: {
    width: '12%',
    marginLeft: '2%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  imgback: {
    width: '70%',
    height: 30,
    marginLeft: '10%',
  },
  txtback: {
    fontSize: 20,
    // marginTop: '1%',
    marginLeft: '2%',
    // marginRight:'2%',
    fontWeight: 'bold',
    color: 'black',
  },
  viewnama: {
    backgroundColor: '#fff',
    width: '70%',
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    alignSelf: 'center',
    marginTop: '20%',
    elevation: 10,
  },
  inputnama: {
    width: '100%',
    height: 50,
    borderWidth: 0.5,
    borderRadius: 20,
    fontWeight: 'bold',
  },
  viewtelpon: {
    backgroundColor: '#fff',
    width: '70%',
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    alignSelf: 'center',
    marginTop: '8%',
    elevation: 10,
  },
  inputtelpon: {
    width: '100%',
    height: 50,
    borderWidth: 0.5,
    borderRadius: 20,
    fontWeight: 'bold',
  },
  viewdata: {
    width: '80%',
    height: 100,
    //   backgroundColor:'red',
    alignSelf: 'center',
    marginTop: '5%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  inputberat: {
    width: '100%',
    borderWidth: 0.5,
    borderRadius: 20,
    // marginLeft:'5%',
    fontWeight: 'bold',
    backgroundColor: '#fff',
    color: 'black',
  },
  viewpicker: {
    width: '40%',
    height: 50,
    backgroundColor: '#fff',
    borderRadius: 30,
    // marginTop:'5%',
    elevation: 8,
    alignSelf: 'center',
    borderWidth: 0.5,
  },
  viewberat: {
    // backgroundColor:'red',
    alignItems: 'center',
    justifyContent: 'center',
    width: '40%',
    borderRadius: 20,
    elevation: 10,
  },
  viewalamat: {
    backgroundColor: 'red',
    width: '70%',
    alignSelf: 'center',
    borderRadius: 20,
    elevation: 10,
  },
  inputalamat: {
    width: '100%',
    backgroundColor: '#fff',
    borderWidth: 0.5,
    borderRadius: 20,
    fontWeight: 'bold',
    maxHeight: 150,
  },
  touchdata: {
    width: '70%',
    height: 50,
    backgroundColor: '#ddd',
    alignSelf: 'center',
    marginTop: '15%',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 20,
    elevation: 10,
  },
  txtdata: {
    fontSize: 15,
    fontWeight: 'bold',
  },
  imgloading: {
    width: '100%',
    height: 200,
    alignSelf: 'center',
    marginTop: '20%',
  },
  txttunggu: {
    fontSize: 18,
    fontWeight: 'bold',
    alignSelf: 'center',
    marginTop: '20%',
  },
  imgloading2: {
    width: '150%',
    height: 150,
  },
});
