import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    // backgroundColor:'#c4ffc4',
    backgroundColor: '#fff',
    flex: 1,
    alignItems: 'center',
  },
  imgback: {
    width: '8%',
    height: 30,
    marginTop: '4%',
  },
  touchback: {
    flexDirection: 'row',
    alignSelf: 'center',
  },
  txtback: {
    fontSize: 20,
    marginTop: '5%',
    marginRight: '60%',
    marginLeft: '5%',
    fontWeight: 'bold',
    color: 'black',
  },
  imgregister: {
    width: '60%',
    height: 200,
    marginTop: '10%',
    alignSelf: 'center',
  },
  container2: {
    width: '99%',
    height: 520,
    backgroundColor: '#c4ffc4',
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    alignItems: 'center',
    // justifyContent:'center'
  },
  viewname: {
    width: '90%',
    height: 50,
    backgroundColor: '#fff',
    marginTop: 30,
    opacity: 0.9,
    borderRadius: 20,
    elevation: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  inputname: {
    width: '75%',
    marginLeft: 10,
  },
  imgname: {
    width: '10%',
    height: 31,
    marginRight: '3%',
  },
  viewemail: {
    width: '90%',
    height: 50,
    backgroundColor: '#fff',
    marginTop: 10,
    opacity: 0.9,
    borderRadius: 20,
    elevation: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  inputemail: {
    width: '75%',
    marginLeft: 10,
  },
  imgemail: {
    width: '15%',
    height: 30,
    marginRight: '1%',
  },
  viewpassword: {
    width: '90%',
    height: 50,
    backgroundColor: '#fff',
    marginTop: 10,
    opacity: 0.9,
    borderRadius: 20,
    elevation: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  inputpassword: {
    width: '75%',
    marginLeft: 10,
  },
  imgpassword: {
    width: '80%',
    height: 30,
    marginRight: '13%',
  },
  viewconfirm: {
    width: '90%',
    height: 50,
    backgroundColor: '#fff',
    marginTop: 10,
    opacity: 0.9,
    borderRadius: 20,
    elevation: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  inputconfirm: {
    width: '75%',
    marginLeft: 10,
  },
  imgconfirm: {
    width: '80%',
    height: 30,
    marginRight: '13%',
  },
  viewnumber: {
    width: '90%',
    height: 50,
    backgroundColor: '#fff',
    marginTop: 10,
    opacity: 0.9,
    borderRadius: 20,
    elevation: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  inputnumber: {
    width: '75%',
    marginLeft: 10,
  },
  imgnumber: {
    width: '8%',
    height: 25,
    marginRight: '2%',
  },
  viewaddress: {
    width: '90%',
    height: 75,
    backgroundColor: '#fff',
    marginTop: 10,
    opacity: 0.9,
    borderRadius: 20,
    elevation: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  inputaddress: {
    width: '75%',
    height: 75,
    marginLeft: 10,
  },
  imgaddress: {
    width: '10%',
    height: 40,
    marginRight: '2%',
  },
  touchregister: {
    width: '90%',
    height: 50,
    backgroundColor: '#ddd',
    marginTop: 40,
    opacity: 0.9,
    borderRadius: 20,
    elevation: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    
  },
  txttouchregister: {
    fontSize: 15,
    color: 'black',
    fontWeight: 'bold',
  },
  imgloading: {
    width: '150%',
    height: 150,
  },
});
